---

name: main

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Stellaris Automation Operator version.'
        required: true
        default: ''
      confirm:
        description: 'Are you sure? Set this to yes.'
        required: true
        default: 'no'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push devel image
    steps:
      - uses: actions/checkout@v5

      - name: Log into registry quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef    # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}


      - name: Build and Store Image @ghcr
        run: |
          IMG=quay.io/stellaris/stellaris-automation-operator:${{ github.event.inputs.version }} make docker-buildx

